enhancement:
 - head-branch: [feat, Feat, FEAT]

repo:
- any:
  - head-branch: [repo, Repo, REPO, ci, CI]
  - changed-files:
    - any-glob-to-any-file: .github

bugfix:
  - head-branch: [^fix, ^bug, ^Fix, ^FIX, ^Bug, ^BUG]

refactor:
  - head-branch: [^refactor, ^Refactor]
